# add unit test later

trigger:
  branches:
    include:
    - '*'
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g swagger-cli@2.3.4
    swagger-cli validate ./swagger/swagger.yaml
  displayName: 'Swagger file validation'
