version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - echo Insert credentials
      - DB_URI=$DBURI
      - cd src/repositories
      - echo Inserting databse connection uri
      - sed -i "s|DB-CONNECTION|$DB_URI|g" mongo_config.py
      - echo Done
      - cd ../..
  build:
    commands:
      - echo Building...
      - echo Build started on `date`
      - ./scripts/build.sh
  post_build:
    commands:
      - echo Build completed on `date`
      - version=0.0.3
      - artifact_name=sensor-inventory-dist
      - cp ./"$artifact_name".zip ./$artifact_name-$version.zip

artifacts:
  files:
    - $artifact_name*.zip
  name: vape-sensor-inventory
